### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference

### ISSUE THREAD

**Issue by 1008k** [NIFCLOUD-mbaas/ncmb_android#224]
Ceashlyticsで稀にエラーが報告されます。
エラーメッセージを記しておきますので可能なら改善いただけましたら幸いです。

- SDKのバージョン(SDK version)
Android 3.0.4

- 不具合が発生した環境(Environment requirement)
Android6~10の複数のベンダーの機種

- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
以下のようなコードをアプリ起動時に書いています。
```
NCMB.initialize(getApplicationContext(), "APP_KEY", "CLIENT_KEY");
NCMBPush.trackAppOpened(getIntent());
```

- エラーメッセージ(Error messages)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
       at com.nifcloud.mbaas.core.NCMBInstallationUtils$2.done(NCMBInstallationUtils.java:117)
       at com.nifcloud.mbaas.core.NCMBQuery$4.done(NCMBQuery.java:118)
       at com.nifcloud.mbaas.core.NCMBInstallationService$5.handleError(NCMBInstallationService.java:478)
       at com.nifcloud.mbaas.core.NCMBService$1.done(NCMBService.java:266)
       at com.nifcloud.mbaas.core.NCMBConnection$StaticAsyncTask.onPostExecute(NCMBConnection.java:270)
       at com.nifcloud.mbaas.core.NCMBConnection$StaticAsyncTask.onPostExecute(NCMBConnection.java:243)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6719)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:467)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。

順次、優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend をどうぞよろしくお願いいたします。

**Comment by ncmbadmin** [comment]
お世話になっております。
ご指摘ありがとうございました。
issue登録いただきました内容の修正が完了しました。
詳細については[v4.0.1](https://github.com/NIFCLOUD-mbaas/ncmb_android/releases/tag/v4.0.1)の内容をご確認ください。

今後とも、mobile backend をどうぞよろしくお願いいたします。
