### ISSUE TITLE
NCMBInstallationUtilsの処理にてjava.lang.NullPointerException例外発生について

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCLOUD-mbaas/ncmb_android#267]
## 不具合の概要(Description of bug)

お問合せにより、以下のように、アプリのクラッシュ監視（Crashlytics）にてエラーが報告されています。
以前、類似現象として issue #224 があり、改修を実施されましたが、改修内容が不完全の可能性があるため、
再度、改修を検討するために、issueを登録しました。

- SDKのバージョン(SDK version): v4.0.1 
- 不具合が発生した環境(Environment requirement)
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
- エラーメッセージ(Error messages)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at com.nifcloud.mbaas.core.NCMBInstallationUtils$2.done(NCMBInstallationUtils.java:117)
       at com.nifcloud.mbaas.core.NCMBQuery$4.done(NCMBQuery.java:118)
       at com.nifcloud.mbaas.core.NCMBInstallationService$5.handleError(NCMBInstallationService.java:478)
       at com.nifcloud.mbaas.core.NCMBService$1.done(NCMBService.java:266)
       at com.nifcloud.mbaas.core.NCMBConnection$StaticAsyncTask.onPostExecute(NCMBConnection.java:270)
       at com.nifcloud.mbaas.core.NCMBConnection$StaticAsyncTask.onPostExecute(NCMBConnection.java:243)
<<省略>>
```

**Comment by watanabe-tomoya** [comment]
- nullチェックを追加
  - if(results.size() > 0 && results != null) ←×(クラッシュしてしまう)
  - if(results != null && results.size() > 0) ←〇
